version: '3'

services:

  portal:
    build:
      context: ./ux
    image: akv-audit-ux
    environment:
      - JAEGER_SERVICE_NAME=akv-portal-jaeger
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    ports:
      - 777:777
    depends_on:
      - rabbitmq
      - jaeger
    restart: on-failure

  audit-srv:
    build:
      context: ./license-audit-service
    image: akv-audit-srv
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 15s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - portal
      - audit-srv
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.12
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268