version: '3'

services:
  portal:
    build:
      context: ./ux
    image: akv-audit-ux
    ports:
      - 777:777
    depends_on:
      - rabbitmq
    restart: on-failure
  audit-srv:
    build:
      context: ./license-audit-service
    image: akv-audit-srv
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5